name: CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  Tests:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SDK_REPO_PRIVATE_KEY }}
    - name: Build and Test
      env:
        CLIENT_TOKEN: ${{ secrets.CONFIDENCE_CLIENT_TOKEN }}
      run: scripts/run_tests.sh $CLIENT_TOKEN

  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --config .swiftlint.yml
